name: ArXiv Scraper Daily Run

on:
  schedule:
    - cron: '0 7 * * *'  # Run every day at 7:00 AM UTC (9:00 AM UTC+2)
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ArXiv scraper
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        DICORD_NEW_RESEARCH_CHANNEL_ID: ${{ secrets.DICORD_NEW_RESEARCH_CHANNEL_ID }}
      run: python AI_paper.py