name: Run AI News Script Daily

on:
  schedule:
    - cron: '0 12 * * *'  # Run every day at 12:00 PM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'  # Specify Python version 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp discord.py python-dotenv nltk

    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('punkt_tab')"

    - name: Debug - List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "Contents of the current directory:"
        ls -la

    - name: Run script
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        if [ -n "$NEWS_API_KEY" ]; then
          echo "NEWS_API_KEY is set"
        else
          echo "NEWS_API_KEY is not set"
          exit 1
        fi
        if [ -n "$DISCORD_WEBHOOK_URL" ]; then
          echo "DISCORD_WEBHOOK_URL is set"
        else
          echo "DISCORD_WEBHOOK_URL is not set"
          exit 1
        fi
        
        # Check if main.py exists
        if [ -f "main.py" ]; then
          echo "main.py found, running script"
          python main.py
        else
          echo "Error: main.py not found"
          echo "Python files in the current directory:"
          ls *.py
          exit 1
        fi