name: Run AI News Script Daily

on:
  schedule:
    - cron: '0 12 * * *'  # Run every day at 12:00 PM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp discord.py python-dotenv nltk

    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"

    - name: Run script
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        echo "NEWS_API_KEY is set: ${{ secrets.NEWS_API_KEY != '' }}"
        echo "DISCORD_WEBHOOK_URL is set: ${{ secrets.DISCORD_WEBHOOK_URL != '' }}"
        python paste.txt